global:

# The root route on which each incoming alert enters.
route:
  # default route if none match
  receiver: alert-buffer-wh
  repeat_interval: {{ ocp_prometheus_alert_repeat }}
  # The labels by which incoming alerts are grouped together. For example,
  # multiple alerts coming in for cluster=A and alertname=LatencyHigh would
  # be batched into a single group.
  # TODO:
  group_by: []

  # All the above attributes are inherited by all child routes and can
  # overwritten on each.
receivers:
- name: alert-buffer-wh
  webhook_configs:
  - url: http://{{ ocp_fluentd_proemtheus_service }}.{{ openshift_logging_namespace }}.svc.cluster.local:{{ ocp_fluentd_prometheus_port }}

