---

- name: iptables config backup
  copy:
    remote_src: true
    src: /etc/sysconfig/iptables
    dest: /etc/sysconfig/.ocp_backup_iptables
    backup: yes
  register: backup

# iptables change
#-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 9100 -j ACCEPT
- name: iptables add node-exporter port
  lineinfile:
    path: /etc/sysconfig/iptables
    regexp: "-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 9100 -j ACCEPT"
    line: "-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 9100 -j ACCEPT"
    insertbefore: "COMMIT" 
  notify: iptables restart
  register: set1

- name: iptables add fluentd port
  lineinfile:
    path: /etc/sysconfig/iptables
    regexp: "-A OS_FIREWALL_ALLOW -p {{ ocp_fluentd_prometheus_protocol }} -m state --state NEW -m {{ ocp_fluentd_prometheus_protocol }} --dport {{ ocp_fluentd_prometheus_port }} -j ACCEPT"
    line: "-A OS_FIREWALL_ALLOW -p {{ ocp_fluentd_prometheus_protocol }} -m state --state NEW -m {{ ocp_fluentd_prometheus_protocol }} --dport {{ ocp_fluentd_prometheus_port }} -j ACCEPT"
    insertbefore: "COMMIT"
  notify: iptables restart
  register: set2


