apiVersion: v1
kind: Service
metadata:
  name: logging-fluentd
spec:
  selector:
    component: fluentd
    provider: openshift
  type: ClusterIP
  ports:
  - nodePort: 0
    port: 8085
    protocol: TCP
    targetPort: 8085

